name: unifold
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1=*cuda*
  - pytorch-cuda=11.7
  - mkl<2024.1 # https://github.com/pytorch/pytorch/issues/123097
  - bioconda::hmmer=3.3
  - bioconda::hhsuite=3.3
  - bioconda::kalign2=2.04
  - tensorboardx
  - biopython
  - numpy
  - scipy
  - pandas
  - python-lmdb
  - ml-collections
  - tokenizers
  - wandb
  - tqdm
  - pip
  - pip:
    - https://github.com/dptech-corp/Uni-Core/releases/download/0.0.3/unicore-0.0.1+cu117torch2.0.0-cp310-cp310-linux_x86_64.whl
